Justin/spring cleaning
Da-Scher/br3ezy pull request #54
Opened 2024-03-09 21:00 UTC by justinsprecco

# Big Changes!

- In order to streamline further development I created a separation in the client side and server side development. Each will reside in their own folders: `client` and `server`, respectively, this is using the node workspaces magic.
- They each have their own package.json allowing a clearer separation of dependencies for the client and server.
- I moved the certificates out of the `dist` folder and created a `certs` folder in the root that will hold the `.pem` pair.
- README now contains information for building the application. 
- `.env` moved to the `server` folder.
- To run a script specific for the client or server, you can either change directories into each or append `-w client` or `-w server` from root.
- Hope these changes aren't too ambitious. Let me know if you have any reservations to this structure.

2024-03-09 21:43 UTC, joebarteluce approved these changes
Beautiful. Things are looking very good here.

I did run into an error about a missing package: "An unhandled exception occurred: The package "@esbuild/darwin-x64" could not be found, and is needed by esbuild."

I was able to resolve this by manually installing this package with `npm install esbuild`.

After that, everything worked as expected. This will be a great place to start again after break.

2024-03-19 17:59 UTC, Da-Scher commented on server/src/app.js
Nice cleanup on the file paths!

2024-03-19 18:03 UTC, Da-Scher requested changes
Delete the .DS_Store file and then this will be approved
Great work

2024-03-19 18:03 UTC, Da-Scher commented on server/src/db/db.js
One question: Are we changing to double quotes for everything or just packages? 
This might be a good time to add `prettier` if we haven't already.

2024-03-19 18:03 UTC, Da-Scher commented on src/.DS_Store
TODO: Delete me

2024-03-19 18:03 UTC, Da-Scher commented on README.md
Good work on the README.

2024-03-19 18:03 UTC, Da-Scher commented on .gitignore
I see, you added gitignores to the two directories, really nice!

2024-03-19 18:10 UTC, justinsprecco commented on server/src/db/db.js
I've just been using prettier on my end, so when I save a file, it's automatic for me.

2024-03-19 18:14 UTC, merged