Dakota/federated livestreams
Da-Scher/br3ezy pull request #57
Opened 2024-03-27 06:04 UTC by Da-Scher

In this pull request: 
1. br3ezy now accepts requests to change federation members data. These requests are handled by sending JSON data that contains information about which br3ezy instance is asking for a change in information. This is handled with a POST request to the API link: `/api/fed/fedeIn`
*Example body of the https request to api/fed/fedeIn*
```json
{
     "fedID": 2
}
```
2. Removed sample streams for future iterations of br3ezy in anticipation of a system that creates stream database objects as the stream occurs. Requesting comment on this point.
3. br3ezy now changes database attribute `isActive` when a stream is live or not. Defaults to `isActive = FALSE`.

2024-03-27 20:24 UTC, joebarteluce approved these changes
I am sad I can no longer watch Nature..

but otherwise, nice work.

2024-03-27 22:02 UTC, justinsprecco requested changes
Not sure how to test this, but it looks like it would work.

** See suggestions

RIP NatureStream

2024-03-28 00:53 UTC, Da-Scher commented on server/src/db/seeds.sql
> +(2, '10.0.0.198', 8000, 2);
I see that the Federation schema should also be (fedPublicId, apiUrl, apiPort) also

2024-03-28 00:55 UTC, Da-Scher commented on server/src/federation/requestUpdate.js
> +const JSON = require('circular-json');
This is required to send the request body in a json string.
Used by line 7.

2024-03-28 00:57 UTC, Da-Scher commented on server/package.json
> +    "circular-json": "^0.5.9",
Going to agree actually.

2024-03-28 15:45 UTC, justinsprecco requested changes
Fix the seeds fix and you're approved.

2024-03-28 15:45 UTC, justinsprecco commented on server/src/db/seeds.sql
> +--(2, '10.0.0.198', 8000, 2);
```suggestion
-- Sample federation member
-- INSERT INTO Federation (fedPublicId, apiUrl, apiPort) VALUES
-- (2, '10.0.0.198', 8000, 2);
```

MySQL complained again, this time due to the lack of space after the comment delimiter.

2024-03-28 15:50 UTC, merged