Justin/add gitignore
Da-Scher/br3ezy pull request #6
Opened 2024-01-29 22:53 UTC by JSprecco

Added the .gitignore and json files to complete the initial repo. Also made a mistake on the README and reverted it to the original.

2024-01-29 23:05 UTC, joebarteluce approved these changes

2024-01-30 06:57 UTC, Da-Scher requested changes
Check the review for my comments on the `package-lock.json` file.
Steps to get this PR approved:
- [x ] ~~add `package-lock.json` to the file `.gitignore` to your local repo.~~
- [x ] ~~use the command `git rm .package-lock.json`~~
- [x] if you have `package-lock.json` in the `.gitignore`, remove `package-lock.json` from `.gitignore`
- [x] `npm audit` to check for vulnerable packages
- [x] `npm audit fix` to update vulnerable versions
- [x] `git add` the changes
- [x] `git push` to your branch

2024-01-30 06:57 UTC, Da-Scher commented on package-lock.json
I was wrong, package-lock.json  we should add the file with 12K lines to the .gitignore

2024-01-30 07:39 UTC, JSprecco commented on package-lock.json
It may be large but having it in the repo will gaurentee the dependencies are met on all of our individual builds.

2024-01-30 14:07 UTC, Da-Scher commented on package-lock.json
On further inspection, you are correct that package-lock.json is necessary even at its size. I will update the requirements for the merge to address the '2 high risk vulnerabilities' with Vite.

2024-01-30 15:28 UTC, JSprecco commented on package-lock.json
I'm getting 0 vulnerabilities on my end.

2024-01-30 15:29 UTC, merged